=== Hartecky/XML-Simple-Protein-Dataset/Project_3/protein.dtd
<!ELEMENT protdataset (protein, function, localisation, sequence, structures)>

<!ELEMENT protein (nazwa?,ID?,gene+,organism*)>
	<!ELEMENT nazwa (#PCDATA)>
	<!ELEMENT ID (#PCDATA)>
	<!ELEMENT gene (#PCDATA)>
	<!ELEMENT organism (#PCDATA)>

<!ELEMENT function (molecular | biological)+ >
	<!ELEMENT molecular (#PCDATA)>
	<!ELEMENT biological (#PCDATA)>

<!ELEMENT localisation (tissue | subcell)+>
	<!ELEMENT tissue (#PCDATA)>
	<!ELEMENT subcell (#PCDATA)>

<!ELEMENT sequence (nucleotide | aminoacids)+>
	<!ELEMENT nucleotide (#PCDATA)>
	<!ELEMENT aminoacids (#PCDATA)>

<!ELEMENT structures (first?,second?,third?,fourth?)>
	<!ELEMENT first EMPTY>
		<!ATTLIST first 
			src	CDATA	#REQUIRED
			alt	CDATA 	#REQUIRED
			height	CDATA 	#IMPLIED
			width	CDATA 	#IMPLIED >
	<!ELEMENT second EMPTY>
		<!ATTLIST second
			src	CDATA	#REQUIRED
			alt	CDATA	#REQUIRED
			height	CDATA	#IMPLIED
			width	CDATA	#IMPLIED >
	<!ELEMENT third EMPTY>
		<!ATTLIST third
			src	CDATA	#REQUIRED
			alt	CDATA	#REQUIRED
			height	CDATA	#IMPLIED
			width	CDATA	#IMPLIED >
	<!ELEMENT fourth EMPTY>
		<!ATTLIST fourth
			src	CDATA	#REQUIRED
			alt	CDATA	#REQUIRED
			height	CDATA	#IMPLIED
			width	CDATA	#IMPLIED >

=== Hartecky/XML-Simple-Protein-Dataset/Project_2/hemoglobin_protein_sec_incorrect.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE protein SYSTEM "protein.dtd">

<protdataset>
	<protein>
		<nazwa>Hemoglobina łańcucha gamma-2</nazwa>
		<ID>P69892</ID>
		<gene>HBG2</gene>
		<organism>Homo sapiens</organism>
	</protein>

	<function>
		<molecular>
			Wiązanie hemu
		</>

		<molecular>
			Wiązanie hemoglobiny alpha
		</>

		<molecular>
			Wiązanie jonów metali
		</>

		<molecular>
			Wiązanie kwasów organicznych 
		</>

		<molecular>
			Wiązanie tlenu 
		</>
			 
		<molecular>
			Aktywność nośnika tlenu
		</>
		<biological>
			Mechanizm krzepnięcia krwi
		</>

		<biological>
			Detoksykacja utleniaczy komórkowych
		</>
		
		<biological>
			Proces kataboliczny nadtlenku wodoru
		</>			<!-- źle pozamykane znaczniki -->
	</function>

	<localisation>
		<tissue>Krew</tissue>
		<subcell>Cytosol</subcell>
		<subcell>Kompleks hemoglobiny</subcell>
	</localisation>

	<sequence>
		<nucleotide>
			ATGGGCCATTTTACCGAAGAAGATAAAGCGACCATTACCAGCCTGTGGGGCAAAGTGAAC
			GTGGAAGATGCGGGCGGCGAAACCCTGGGCCGCCTGCTGGTGGTGTATCCGTGGACCCAG
			CGCTTTTTTGATAGCTTTGGCAACCTGAGCAGCGCGAGCGCGATTATGGGCAACCCGAAA
			GTGAAAGCGCATGGCAAAAAAGTGCTGACCAGCCTGGGCGATGCGATTAAACATCTGGAT
			GATCTGAAAGGCACCTTTGCGCAGCTGAGCGAACTGCATTGCGATAAACTGCATGTGGAT
			CCGGAAAACTTTAAACTGCTGGGCAACGTGCTGGTGACCGTGCTGGCGATTCATTTTGGC
			AAAGAATTTACCCCGGAAGTGCAGGCGAGCTGGCAGAAAATGGTGACCGGCGTGGCGAGC
			GCGCTGAGCAGCCGCTATCAT
		</nucleotide>
		<aminoacids>
			MGHFTEEDKATITSLWGKVNVEDAGGETLGRLLVVYPWTQRFFDSFGNLSSASAIMGNPK
			VKAHGKKVLTSLGDAIKHLDDLKGTFAQLSELHCDKLHVDPENFKLLGNVLVTVLAIHFG
			KEFTPEVQASWQKMVTGVASALSSRYH
		</aminoacids>
	</sequence>

	<structures>
		<first src="first_hemoglobin.png" alt="first_hemoglobin_alt.png"></first>
		<second src="second_hemoglobin.png" alt="second_hemoglobin_alt.png"></second>
		<third src="third_hemoglobin.png" alt="third_hemoglobin_alt.png"></third>
		<fourth src="fourth_hemoglobin.png" alt="fourth_hemoglobin_alt.png"></fourth>
	</structures>

</protdataset>

=== Hartecky/XML-Simple-Protein-Dataset/Project_2/main_protein.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE protein SYSTEM "protein.dtd">

<protdataset>
	<protein>
		<nazwa>Białko Rieskego</nazwa>
		<ID>Q9ZR03</ID>
		<gene>PetC</gene>
		<organism>Arabidopsis Thaliana</organism>
	</protein>

	<function>
		<molecular>
			Wiązanie centrum żelazowo-siarkowego
		</molecular>

		<molecular>
			Transport elektronów 
		</molecular>

		<molecular>
			Wiązanie jonów metali
		</molecular>

		<molecular>
			Reduktaza cytochromu c
		</molecular>

		<biological>
			Czynny udział w fotosyntetycznym transporcie elektronów
		</biological>

		<biological>
			Mechanizm obronny rośliny przed nadmierną ilością promieniowania słonecznego
		</biological>

		<biological>
			Optymalizowanie wydajności procesu fotosyntezy
		</biological>
	</function>

	<localisation>
		<tissue>Liść</tissue>
		<subcell>Chloroplasty</subcell>
		<subcell>Tylakoidy</subcell>
		<subcell>Błona tylakoidów</subcell>
	</localisation>

	<sequence>
		<nucleotide>
			GTTGCCTTGTACTAGCTCTTACACCTGAGCTCCACTATTTTATAGCACAATGGCCATGCT
			GTCCTCCCGCCGTGTGGCCGCCCCGGCCAAGGCTTCGGCCATTCGCCGCTCGCGCGTTAT
			GCCGGTGGTGCGCGCTGCCGCTGCCTCGTCGGAGGTGCCCGACATGAACAAGCGCAACAT
			CATGAACCTGATCCTGGCTGGTGGCGCTGGTCTGCCCATCACCACCCTGGCTCTGGGCTA
			CGGTGCCTTCTTCGTGCCCCCCAGCTCTGGCGGTGGCGGCGGTGGCCAGGCCGCTAAGGA
			CGCTCTGGGCAACGACATCAAGGCCGGGGAGTGGCTGAAGACCCACCTGGCTGGTGACCG
			CTCGCTGTCCCAGGGCCTGAAGGGTGACCCCACCTACCTGATCGTCACCGCCGACAGCAC
			CATCGAGAAGTACGGCCTGAACGCCGTGTGCACTCACCTGGGCTGCGTCGTGCCTTGGGT
			GGCGGCCGAGAACAAGTTCAAGTGCCCTTGCCACGGCTCTCAGTACAACGCTGAGGGCAA
			GGTGGTCCGTGGCCCCGCTCCCCTGTCGCTGGCCCTGGCCCACTGCGACGTGGCTGAGTC
			TGGCCTGGTCACCTTCTCCACCTGGACGGAGACTGACTTCCGTACCGGCCTGGAGCCCTG
			GTGGGCGTAAATCCGCTCCTGCTACTGCCGCGTTTTGACGGCGCAGCTGCTACAGCCGCG
			GCCCGCGTGTTGATTGTCTCTCTCAGCCAGGCCGCTTCGGCGGCGGCCACGTTCGCTGCT
			GGTGAAGCAGTGGACGCGGGGGCGGGAGGCCGGAGCGTGGAGCTGCGGCGGCAGCAGCAG
			CGGCGCCAGGCAGTGCTGGGCGTGTCGCTTGTACGTTGTTGCTGATGAGTGGAGGAGATG
			ACAAGGGCGGGAGCAGAGCAGGAGGGCCTGGGGGCAGCGTCTGCCGGCCGTGCGCACCGG
			ACCCTGGCCGCCACGGAGGAAGTTTTGGTTCCGGGCGCCGTCGCGCTCTTACGCGCGGGC
			GCCTTTTCTGTGGCGTACCCAGGGGAATTTTTAGCGTGCCGCGGTCTGGTGCATAGGGGC
			GCGTGTGGGGCGCTAGCGCGTCCCGTGGCGGCGGGCCGAATGGCCGTGTCGCCCACCCGC
			AGCGCTCCTTTGCCAGGGTGTGCCGACCCGGCACGCGGGCGTGTTACGTTTCGGGCTCTG
			AGCGGGCGGTTGCTGTGTCGGTGTGGGTTTGGCACCGGACGTAGCGGCGTGGCACTGGGC
			GTCGCGATGAGGGAGAGTGGAGAAGACTTCAGAGATTATTGCGTTAGTGCATTTGATGCA
			AATTAAGAGTCGATGCCTCTCGGGCGGCGGGCCTGGTGCTGCCGCCGGGGGCGGGTGCCA
			TGTGAATGCTGCGCCGTGCCCGCGGCGGACGCATGCGCCTGTAACTCGGAAGAACC
		</nucleotide>
		<aminoacids>
			MASSSLSPATQLGSSRSALMAMSSGLFVKPTKMNHQMVRKEKIGLRISCQASSIPADRVP
			DMEKRKTLNLLLLGALSLPTGYMLVPYATFFVPPGTGGGGGGTPAKDALGNDVVAAEWLK
			THGPGDRTLTQGLKGDPTYLVVENDKTLATYGINAVCTHLGCVVPWNKAENKFLCPCHGS
			QYNAQGRVVRGPAPLSLALAHADIDEAGKVLFVPWVETDFRTGDAPWWS
		</aminoacids>
	</sequence>

	<structures>
		<first src="first.png" alt="first_alt.png"></first>
		<second src="second.png" alt="second_alt.png"></second>
		<third src="third.png" alt="third_alt.png"></third>
		<fourth src="fourth.png" alt="fourth_alt.png"></fourth>
	</structures>

</protdataset>

=== Hartecky/XML-Simple-Protein-Dataset/Project_3/hemoglobin_protein.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="example.xsl" type="text/xsl" ?>
<!DOCTYPE protein SYSTEM "protein.dtd">

<protdataset>
	<protein>
		<nazwa>Hemoglobina łańcucha gamma-2</nazwa>
		<ID>P69892</ID>
		<gene>HBG2</gene>
		<organism>Homo sapiens</organism>
	</protein>

	<function>
		<molecular>
			Wiązanie hemu
		</molecular>

		<molecular>
			Wiązanie hemoglobiny alpha
		</molecular>

		<molecular>
			Wiązanie jonów metali
		</molecular>

		<molecular>
			Wiązanie kwasów organicznych 
		</molecular>

		<molecular>
			Wiązanie tlenu 
		</molecular>
			 
		<molecular>
			Aktywność nośnika tlenu
		</molecular>
		<biological>
			Mechanizm krzepnięcia krwi
		</biological>

		<biological>
			Detoksykacja utleniaczy komórkowych
		</biological>
		
		<biological>
			Proces kataboliczny nadtlenku wodoru
		</biological>
	</function>

	<localisation>
		<tissue>Krew</tissue>
		<subcell>Cytosol</subcell>
		<subcell>Kompleks hemoglobiny</subcell>
	</localisation>

	<sequence>
		<nucleotide>
			ATGGGCCATTTTACCGAAGAAGATAAAGCGACCATTACCAGCCTGTGGGGCAAAGTGAAC
			GTGGAAGATGCGGGCGGCGAAACCCTGGGCCGCCTGCTGGTGGTGTATCCGTGGACCCAG
			CGCTTTTTTGATAGCTTTGGCAACCTGAGCAGCGCGAGCGCGATTATGGGCAACCCGAAA
			GTGAAAGCGCATGGCAAAAAAGTGCTGACCAGCCTGGGCGATGCGATTAAACATCTGGAT
			GATCTGAAAGGCACCTTTGCGCAGCTGAGCGAACTGCATTGCGATAAACTGCATGTGGAT
			CCGGAAAACTTTAAACTGCTGGGCAACGTGCTGGTGACCGTGCTGGCGATTCATTTTGGC
			AAAGAATTTACCCCGGAAGTGCAGGCGAGCTGGCAGAAAATGGTGACCGGCGTGGCGAGC
			GCGCTGAGCAGCCGCTATCAT
		</nucleotide>
		<aminoacids>
			MGHFTEEDKATITSLWGKVNVEDAGGETLGRLLVVYPWTQRFFDSFGNLSSASAIMGNPK
			VKAHGKKVLTSLGDAIKHLDDLKGTFAQLSELHCDKLHVDPENFKLLGNVLVTVLAIHFG
			KEFTPEVQASWQKMVTGVASALSSRYH
		</aminoacids>
	</sequence>

	<structures>
		<first src="first_hemoglobin.png" alt="first_hemoglobin_alt.png"></first>
		<second src="second_hemoglobin.png" alt="second_hemoglobin_alt.png"></second>
		<third src="third_hemoglobin.png" alt="third_hemoglobin_alt.png"></third>
		<fourth src="fourth_hemoglobin.png" alt="fourth_hemoglobin_alt.png"></fourth>
	</structures>

</protdataset>

=== Hartecky/XML-Simple-Protein-Dataset/Project_2/hemoglobin_protein_incorrect.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE protein SYSTEM "protein.dtd">

<protdataset>
	<protein>
		<nazwa>Hemoglobina łańcucha gamma-2</nazwa>
		<nazwa>Hemoglobina</nazwa>			<!-- znacznik nazwa użyty dwa razy a wymuszone było 0 albo 1 -->
		<organism>Homo sapiens</organism>	<!-- nie ma znaczników gen i ID które były wymagane -->
	</protein>

	<function>
		<molecular>
			Wiązanie hemu
		</molecular>

		<molecular>
			Wiązanie hemoglobiny alpha
		</molecular>

		<molecular>
			Wiązanie jonów metali
		</molecular>

		<molecular>
			Wiązanie kwasów organicznych 
		</molecular>

		<molecular>
			Wiązanie tlenu 
		</molecular>
			 
		<molecular>
			Aktywność nośnika tlenu
		</molecular>
		<biological>
			Mechanizm krzepnięcia krwi
		</biological>

		<biological>
			Detoksykacja utleniaczy komórkowych
		</biological>
		
		<biological>
			Proces kataboliczny nadtlenku wodoru
		</biological>
	</function>					

	<localisation>
		<tissue>Krew</tissue>
		<subcell>Cytosol</subcell>
		<subcell>Kompleks hemoglobiny</subcell>
	</localisation>

	<sequence>
		<nucleotide>
			ATGGGCCATTTTACCGAAGAAGATAAAGCGACCATTACCAGCCTGTGGGGCAAAGTGAAC
			GTGGAAGATGCGGGCGGCGAAACCCTGGGCCGCCTGCTGGTGGTGTATCCGTGGACCCAG
			CGCTTTTTTGATAGCTTTGGCAACCTGAGCAGCGCGAGCGCGATTATGGGCAACCCGAAA
			GTGAAAGCGCATGGCAAAAAAGTGCTGACCAGCCTGGGCGATGCGATTAAACATCTGGAT
			GATCTGAAAGGCACCTTTGCGCAGCTGAGCGAACTGCATTGCGATAAACTGCATGTGGAT
			CCGGAAAACTTTAAACTGCTGGGCAACGTGCTGGTGACCGTGCTGGCGATTCATTTTGGC
			AAAGAATTTACCCCGGAAGTGCAGGCGAGCTGGCAGAAAATGGTGACCGGCGTGGCGAGC
			GCGCTGAGCAGCCGCTATCAT
		</nucleotide>
		<aminoacids>
			MGHFTEEDKATITSLWGKVNVEDAGGETLGRLLVVYPWTQRFFDSFGNLSSASAIMGNPK
			VKAHGKKVLTSLGDAIKHLDDLKGTFAQLSELHCDKLHVDPENFKLLGNVLVTVLAIHFG
			KEFTPEVQASWQKMVTGVASALSSRYH
		</aminoacids>
	</sequence>

	<structures>
		<first src="first_hemoglobin.png" ></first>
		<second src="second_hemoglobin.png" ></second>
		<third src="third_hemoglobin.png" ></third>
		<fourth src="fourth_hemoglobin.png"></fourth>			<!--nie posiadają elementu alt który był wymagany -->
	</structures>

</protdataset>
